repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-bugbear==24.12.12
            - flake8-comprehensions==3.16.0
            - flake8-unused-arguments==0.0.13

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-setuptools, mypy-extensions, types-pillow]
        exclude: ^(docs/|tests/) 